server:
  port: 8080

spring:
  application:
    name: taxi-booking
  datasource:
    url: jdbc:h2:mem:taxiBooking
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

